Test case
peter6601/TDDFaDaTsaiDemo pull request #2
Opened 2019-09-04 14:13 UTC by peter6601

create a new test case

2019-09-05 15:11 UTC, ghost requested changes
你是不是從 `ssun/discussion` 在 checkout 一個 branch啊？

2019-09-05 15:11 UTC, SteveS0911 commented on Tests/FaTsaiBrain/FaTsaiBrainCaseTests.swift
> +class FaTsaiBrainCaseTests: XCTestCase {
本來不是已經有 `FaTsaiBrainTests` 了嗎？

2019-09-06 03:12 UTC, peter6601 commented on Tests/FaTsaiBrain/FaTsaiBrainCaseTests.swift
> +class FaTsaiBrainCaseTests: XCTestCase {
這個是我測試的，請幫我reject

2019-09-06 03:14 UTC, peter6601 commented
> 你是不是從 `ssun/discussion` 在 checkout 一個 branch啊？

對，等等我先把discussion先merge 回 master後，再開心的branch改我要的東西

2019-09-06 03:20 UTC, closed without merging